{% set name = "spatialcsv" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialcsv-{{ version }}.tar.gz
  sha256: 167c0b6d8127367d847b5c2fa48f57d6350081ed95ae65610f19179c67038769

build:
  entry_points:
    - spatialcsv=spatialcsv.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - folium
    - httpx
    - leafmap
    - ipyleaflet
    - ipywidgets
    - xyzservices

test:
  imports:
    - spatialcsv
  commands:
    - pip check
    - spatialcsv --help
  requires:
    - pip

about:
  home: https://github.com/TJHomer/spatialcsv
  summary: Easily add location points to a map from a csv
  license: GPL-1.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TJHomer
